### ISSUE TITLE
How to save checkpoint during training?

### ISSUE THREAD

**Issue by Lonely-wind** [PavlosMelissinos/enet-keras#13]
Thanks for sharing code!

When I run `train.py`, I found it took a lot of time. I interrupted it during training and found there was not a checkpoint has been saved.
I noticed that there is a `callbacks()` function in the `train.py`. I guess this is used for saving checkpoint. But I didn't see it was called during training.
So how could I save the checkpoint during training periodically? For example, I want to save the checkpoint after trained every 1000 images.

Looking forward to your response. Thank you so much.
@PavlosMelissinos

**Comment by PavlosMelissinos** [comment]
Checkpoints are saved at the end of each epoch (~80k images). Afaik you
can't save more often, unless you extend the Checkpoint callback.
Alternatively you can train on a subset of the dataset by setting your own
sample_size.

Keep in mind that this is still under development and there are numerous
shortcomings that cannot be circumvented at the moment. Don't rely on it!

**Comment by Lonely-wind** [comment]
I think training on subset is a good idea.
Thank you so much!

**Comment by PavlosMelissinos** [comment]
Ok so it seems like this specific question has been answered. I'll be closing the issue for the time being but please reopen it/discuss here if anything comes up.

Anyone interested in this might find the new `OverfittingExperiment` class useful. It randomly picks samples (100 by default) from the dataset and tries to fit the network on it. In theory, that should give you an idea about whether you're going in the right direction. Still working on it though.

I should really make a new repo for non-enet stuff...
