### ISSUE TITLE
SUNRGBD2Dseg = hdf5storage.loadmat(filename)

### ISSUE THREAD

**Issue by WPKENAN** [PavlosMelissinos/enet-keras#23]
您好，我想咨询下为什么卡在这句SUNRGBD2Dseg = hdf5storage.loadmat(filename)将近一个小时还没有进展，谢谢

**Comment by PavlosMelissinos** [comment]
1. I don't speak chinese
2. I can't make sense out of the translation:
> Hello, I would like to ask why the card in this sentence SUNRGBD2Dseg = hdf5storage.loadmat (filename) has not progressed for nearly an hour, thank you
3. This project is practically abandoned so there's little I can do anymore.

Due to the above, I've closed the issue, sorry.
