### ISSUE TITLE
OpenCV dependency removal

### ISSUE THREAD

**Issue by PavlosMelissinos** [PavlosMelissinos/enet-keras#3]
I'm interested in throwing away every ```import cv2``` line because OpenCV has mostly been a pain for no reason. The attempt can be seen [in the no_opencv branch](/PavlosMelissinos/enet-keras/tree/no_opencv)

The strongest contenders are pillow and scikit-image.

I will be documenting my experiences here mostly as notes to myself and possibly to fuel a discussion.

|   Library   | Wraps NumPy | channel order | dimension order |
|-----------|----------------|---------------|------------------|
|  OpenCV  |          yes         |        bgr        |   (width, height)   |
|    Pillow    |          no          |        rgb        |   (width, height)   |
|  skimage  |         yes          |        rgb        |   (height, width)   |

Any suggestions are welcome!

**Comment by PavlosMelissinos** [comment]
I'm going with pillow after all, as the conversion of a PIL.Image to numpy is trivial and pretty much contains every necessary operation. Next few commits will gradually simplify preprocessing (currently a flag determines which library will be used and that unnecessarily increases code complexity).

**Comment by PavlosMelissinos** [comment]
CLAHE is one of the things that does not seem to be supported by pillow. This is not a deal breaker but is anyone aware of an alternative implementation? I know there's equalize in ImageOps but I don't think it uses CLAHE (which works great by the way, I will upload a notebook with a demonstration)

**Comment by PavlosMelissinos** [comment]
[Here is the notebook](https://gist.github.com/PavlosMelissinos/3c59567c0d8470daddeab607f2842d19), unfortunately I couldn't get ipywidgets to show the outputs at all in the static version.

**Comment by mrgloom** [comment]
Can you explain why opencv was dropped?

**Comment by PavlosMelissinos** [comment]
Hey, sorry for taking this long but I haven't been around in general this past year.

It's a personal choice. I prefer lightweight, simple options that stay away from obscurity and opencv is neither. It follows a different approach than most libraries (e.g. bgr vs rgb), sometimes for no good reason, and this project didn't need any of the advanced features of opencv, therefore I decided against using it. Of course as this is an open source project, anyone is free to modify the code and add it. :)
